# Generated by Django 3.1 on 2020-08-31 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.PositiveIntegerField(verbose_name='id группы')),
                ('name', models.CharField(max_length=400, verbose_name='Название группы')),
                ('screen_name', models.CharField(max_length=50, verbose_name='Имя в ссылке')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрытая')),
                ('group_type', models.CharField(max_length=10, verbose_name='Тип')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.TextField(verbose_name='Статус')),
                ('members_count', models.PositiveIntegerField(verbose_name='Кол-во участников')),
                ('wall', models.SmallIntegerField(verbose_name='Степень открытости стены')),
                ('user', models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
