# Generated by Django 3.1.3 on 2020-11-20 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(unique=True, verbose_name='Id from vk')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('screen_name', models.CharField(max_length=200, unique=True, verbose_name='Name from link')),
                ('is_closed', models.BooleanField(verbose_name='Closed')),
                ('description', models.TextField(verbose_name='Description')),
                ('members_count', models.IntegerField(verbose_name='Group members count')),
                ('status', models.CharField(max_length=500, verbose_name='Status')),
                ('photo_200', models.CharField(max_length=500, verbose_name='Link on avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(unique=True, verbose_name='Id from vk')),
                ('from_id', models.IntegerField(verbose_name='Id who post')),
                ('date', models.PositiveBigIntegerField(verbose_name='Date published in unix')),
                ('text', models.TextField(verbose_name='Text')),
                ('comments', models.IntegerField(verbose_name='Comments count')),
                ('likes', models.IntegerField(verbose_name='Likes count')),
                ('reposts', models.IntegerField(verbose_name='Reposts count')),
                ('views', models.IntegerField(verbose_name='Views count')),
                ('link', models.CharField(max_length=500, unique=True, verbose_name='Link on mem')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of request')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='API.group')),
            ],
        ),
    ]
